name: Build and Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23.3'
      - name: Build binary
        run: |
          cd src
          GOOS=linux GOARCH=amd64 go build -ldflags="-s -w -X 'main.Version=${{ github.ref_name }}'" -o ../build/infra .
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: build/infra
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}